//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.21 at 11:39:54 AM COT 
//


package com.ssl.unad.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estudiante">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numEstudiante" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="primerNombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="primerApellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="segundoApellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="programaAcademico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="centro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="periodos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="periodo" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nomPeriodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cursos">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="curso" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="registroAcademico" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                                 &lt;element name="codCurso" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="nomCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="creditos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="tipoCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="nota60" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="nota40" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="nota100" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="fechaGrabacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="observacionNotaCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="promedio_periodo" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="totalCreditosAprobadosPeriodo" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="beneficiarioConvenioPeriodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="promedioHistorico" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="totalCreditoAprobados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="fechaGeneracionReporte" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "estudiante",
    "periodos",
    "promedioHistorico",
    "totalCreditoAprobados",
    "fechaGeneracionReporte"
})
@XmlRootElement(name = "informacion_notas_estudiante")
public class InformacionNotasEstudiante {

    @XmlElement(required = true)
    protected InformacionNotasEstudiante.Estudiante estudiante;
    @XmlElement(required = true)
    protected InformacionNotasEstudiante.Periodos periodos;
    protected float promedioHistorico;
    protected byte totalCreditoAprobados;
    @XmlElement(required = true)
    protected String fechaGeneracionReporte;

    /**
     * Gets the value of the estudiante property.
     * 
     * @return
     *     possible object is
     *     {@link InformacionNotasEstudiante.Estudiante }
     *     
     */
    public InformacionNotasEstudiante.Estudiante getEstudiante() {
        return estudiante;
    }

    /**
     * Sets the value of the estudiante property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacionNotasEstudiante.Estudiante }
     *     
     */
    public void setEstudiante(InformacionNotasEstudiante.Estudiante value) {
        this.estudiante = value;
    }

    /**
     * Gets the value of the periodos property.
     * 
     * @return
     *     possible object is
     *     {@link InformacionNotasEstudiante.Periodos }
     *     
     */
    public InformacionNotasEstudiante.Periodos getPeriodos() {
        return periodos;
    }

    /**
     * Sets the value of the periodos property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacionNotasEstudiante.Periodos }
     *     
     */
    public void setPeriodos(InformacionNotasEstudiante.Periodos value) {
        this.periodos = value;
    }

    /**
     * Gets the value of the promedioHistorico property.
     * 
     */
    public float getPromedioHistorico() {
        return promedioHistorico;
    }

    /**
     * Sets the value of the promedioHistorico property.
     * 
     */
    public void setPromedioHistorico(float value) {
        this.promedioHistorico = value;
    }

    /**
     * Gets the value of the totalCreditoAprobados property.
     * 
     */
    public byte getTotalCreditoAprobados() {
        return totalCreditoAprobados;
    }

    /**
     * Sets the value of the totalCreditoAprobados property.
     * 
     */
    public void setTotalCreditoAprobados(byte value) {
        this.totalCreditoAprobados = value;
    }

    /**
     * Gets the value of the fechaGeneracionReporte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaGeneracionReporte() {
        return fechaGeneracionReporte;
    }

    /**
     * Sets the value of the fechaGeneracionReporte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaGeneracionReporte(String value) {
        this.fechaGeneracionReporte = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numEstudiante" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="primerNombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="primerApellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="segundoApellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="programaAcademico" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="centro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numEstudiante",
        "primerNombre",
        "primerApellido",
        "segundoApellido",
        "programaAcademico",
        "centro"
    })
    public static class Estudiante {

        protected int numEstudiante;
        @XmlElement(required = true)
        protected String primerNombre;
        @XmlElement(required = true)
        protected String primerApellido;
        @XmlElement(required = true)
        protected String segundoApellido;
        @XmlElement(required = true)
        protected String programaAcademico;
        @XmlElement(required = true)
        protected String centro;

        /**
         * Gets the value of the numEstudiante property.
         * 
         */
        public int getNumEstudiante() {
            return numEstudiante;
        }

        /**
         * Sets the value of the numEstudiante property.
         * 
         */
        public void setNumEstudiante(int value) {
            this.numEstudiante = value;
        }

        /**
         * Gets the value of the primerNombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerNombre() {
            return primerNombre;
        }

        /**
         * Sets the value of the primerNombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerNombre(String value) {
            this.primerNombre = value;
        }

        /**
         * Gets the value of the primerApellido property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerApellido() {
            return primerApellido;
        }

        /**
         * Sets the value of the primerApellido property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerApellido(String value) {
            this.primerApellido = value;
        }

        /**
         * Gets the value of the segundoApellido property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSegundoApellido() {
            return segundoApellido;
        }

        /**
         * Sets the value of the segundoApellido property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSegundoApellido(String value) {
            this.segundoApellido = value;
        }

        /**
         * Gets the value of the programaAcademico property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProgramaAcademico() {
            return programaAcademico;
        }

        /**
         * Sets the value of the programaAcademico property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProgramaAcademico(String value) {
            this.programaAcademico = value;
        }

        /**
         * Gets the value of the centro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCentro() {
            return centro;
        }

        /**
         * Sets the value of the centro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCentro(String value) {
            this.centro = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="periodo" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nomPeriodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cursos">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="curso" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="registroAcademico" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                                       &lt;element name="codCurso" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="nomCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="creditos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="tipoCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="nota60" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="nota40" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="nota100" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="fechaGrabacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="observacionNotaCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="promedio_periodo" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="totalCreditosAprobadosPeriodo" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="beneficiarioConvenioPeriodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "periodo"
    })
    public static class Periodos {

        protected List<InformacionNotasEstudiante.Periodos.Periodo> periodo;

        /**
         * Gets the value of the periodo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the periodo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPeriodo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InformacionNotasEstudiante.Periodos.Periodo }
         * 
         * 
         */
        public List<InformacionNotasEstudiante.Periodos.Periodo> getPeriodo() {
            if (periodo == null) {
                periodo = new ArrayList<InformacionNotasEstudiante.Periodos.Periodo>();
            }
            return this.periodo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nomPeriodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cursos">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="curso" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="registroAcademico" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                             &lt;element name="codCurso" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="nomCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="creditos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="tipoCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="nota60" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="nota40" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="nota100" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="fechaGrabacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="observacionNotaCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="promedio_periodo" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="totalCreditosAprobadosPeriodo" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="beneficiarioConvenioPeriodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nomPeriodo",
            "cursos",
            "promedioPeriodo",
            "totalCreditosAprobadosPeriodo",
            "beneficiarioConvenioPeriodo"
        })
        public static class Periodo {

            @XmlElement(required = true)
            protected String nomPeriodo;
            @XmlElement(required = true)
            protected InformacionNotasEstudiante.Periodos.Periodo.Cursos cursos;
            @XmlElement(name = "promedio_periodo")
            protected float promedioPeriodo;
            protected byte totalCreditosAprobadosPeriodo;
            @XmlElement(required = true)
            protected String beneficiarioConvenioPeriodo;

            /**
             * Gets the value of the nomPeriodo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNomPeriodo() {
                return nomPeriodo;
            }

            /**
             * Sets the value of the nomPeriodo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNomPeriodo(String value) {
                this.nomPeriodo = value;
            }

            /**
             * Gets the value of the cursos property.
             * 
             * @return
             *     possible object is
             *     {@link InformacionNotasEstudiante.Periodos.Periodo.Cursos }
             *     
             */
            public InformacionNotasEstudiante.Periodos.Periodo.Cursos getCursos() {
                return cursos;
            }

            /**
             * Sets the value of the cursos property.
             * 
             * @param value
             *     allowed object is
             *     {@link InformacionNotasEstudiante.Periodos.Periodo.Cursos }
             *     
             */
            public void setCursos(InformacionNotasEstudiante.Periodos.Periodo.Cursos value) {
                this.cursos = value;
            }

            /**
             * Gets the value of the promedioPeriodo property.
             * 
             */
            public float getPromedioPeriodo() {
                return promedioPeriodo;
            }

            /**
             * Sets the value of the promedioPeriodo property.
             * 
             */
            public void setPromedioPeriodo(float value) {
                this.promedioPeriodo = value;
            }

            /**
             * Gets the value of the totalCreditosAprobadosPeriodo property.
             * 
             */
            public byte getTotalCreditosAprobadosPeriodo() {
                return totalCreditosAprobadosPeriodo;
            }

            /**
             * Sets the value of the totalCreditosAprobadosPeriodo property.
             * 
             */
            public void setTotalCreditosAprobadosPeriodo(byte value) {
                this.totalCreditosAprobadosPeriodo = value;
            }

            /**
             * Gets the value of the beneficiarioConvenioPeriodo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBeneficiarioConvenioPeriodo() {
                return beneficiarioConvenioPeriodo;
            }

            /**
             * Sets the value of the beneficiarioConvenioPeriodo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBeneficiarioConvenioPeriodo(String value) {
                this.beneficiarioConvenioPeriodo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="curso" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="registroAcademico" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *                   &lt;element name="codCurso" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="nomCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="creditos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="tipoCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="nota60" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="nota40" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="nota100" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="fechaGrabacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="observacionNotaCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "curso"
            })
            public static class Cursos {

                protected List<InformacionNotasEstudiante.Periodos.Periodo.Cursos.Curso> curso;

                /**
                 * Gets the value of the curso property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the curso property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCurso().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link InformacionNotasEstudiante.Periodos.Periodo.Cursos.Curso }
                 * 
                 * 
                 */
                public List<InformacionNotasEstudiante.Periodos.Periodo.Cursos.Curso> getCurso() {
                    if (curso == null) {
                        curso = new ArrayList<InformacionNotasEstudiante.Periodos.Periodo.Cursos.Curso>();
                    }
                    return this.curso;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="registroAcademico" type="{http://www.w3.org/2001/XMLSchema}long"/>
                 *         &lt;element name="codCurso" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="nomCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="creditos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="tipoCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="nota60" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="nota40" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="nota100" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="fechaGrabacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="observacionNotaCurso" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "registroAcademico",
                    "codCurso",
                    "nomCurso",
                    "creditos",
                    "tipoCurso",
                    "nota60",
                    "nota40",
                    "nota100",
                    "fechaGrabacion",
                    "observacionNotaCurso"
                })
                public static class Curso {

                    protected long registroAcademico;
                    protected int codCurso;
                    @XmlElement(required = true)
                    protected String nomCurso;
                    protected byte creditos;
                    @XmlElement(required = true)
                    protected String tipoCurso;
                    protected float nota60;
                    protected float nota40;
                    protected float nota100;
                    @XmlElement(required = true)
                    protected String fechaGrabacion;
                    @XmlElement(required = true)
                    protected String observacionNotaCurso;

                    /**
                     * Gets the value of the registroAcademico property.
                     * 
                     */
                    public long getRegistroAcademico() {
                        return registroAcademico;
                    }

                    /**
                     * Sets the value of the registroAcademico property.
                     * 
                     */
                    public void setRegistroAcademico(long value) {
                        this.registroAcademico = value;
                    }

                    /**
                     * Gets the value of the codCurso property.
                     * 
                     */
                    public int getCodCurso() {
                        return codCurso;
                    }

                    /**
                     * Sets the value of the codCurso property.
                     * 
                     */
                    public void setCodCurso(int value) {
                        this.codCurso = value;
                    }

                    /**
                     * Gets the value of the nomCurso property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNomCurso() {
                        return nomCurso;
                    }

                    /**
                     * Sets the value of the nomCurso property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNomCurso(String value) {
                        this.nomCurso = value;
                    }

                    /**
                     * Gets the value of the creditos property.
                     * 
                     */
                    public byte getCreditos() {
                        return creditos;
                    }

                    /**
                     * Sets the value of the creditos property.
                     * 
                     */
                    public void setCreditos(byte value) {
                        this.creditos = value;
                    }

                    /**
                     * Gets the value of the tipoCurso property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTipoCurso() {
                        return tipoCurso;
                    }

                    /**
                     * Sets the value of the tipoCurso property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTipoCurso(String value) {
                        this.tipoCurso = value;
                    }

                    /**
                     * Gets the value of the nota60 property.
                     * 
                     */
                    public float getNota60() {
                        return nota60;
                    }

                    /**
                     * Sets the value of the nota60 property.
                     * 
                     */
                    public void setNota60(float value) {
                        this.nota60 = value;
                    }

                    /**
                     * Gets the value of the nota40 property.
                     * 
                     */
                    public float getNota40() {
                        return nota40;
                    }

                    /**
                     * Sets the value of the nota40 property.
                     * 
                     */
                    public void setNota40(float value) {
                        this.nota40 = value;
                    }

                    /**
                     * Gets the value of the nota100 property.
                     * 
                     */
                    public float getNota100() {
                        return nota100;
                    }

                    /**
                     * Sets the value of the nota100 property.
                     * 
                     */
                    public void setNota100(float value) {
                        this.nota100 = value;
                    }

                    /**
                     * Gets the value of the fechaGrabacion property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFechaGrabacion() {
                        return fechaGrabacion;
                    }

                    /**
                     * Sets the value of the fechaGrabacion property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFechaGrabacion(String value) {
                        this.fechaGrabacion = value;
                    }

                    /**
                     * Gets the value of the observacionNotaCurso property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getObservacionNotaCurso() {
                        return observacionNotaCurso;
                    }

                    /**
                     * Sets the value of the observacionNotaCurso property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setObservacionNotaCurso(String value) {
                        this.observacionNotaCurso = value;
                    }

                }

            }

        }

    }

}
